window.AIBridge = class AIBridge {
  constructor(state){this.state=state;this.audit=[];}
  manifest(){const object=(properties={},required=[])=>({type:"object",properties,required,additionalProperties:false}),string={type:"string"};return {name:"jiuzhou-strategy",version:"1.0",phase:"planning",connection:{connected:false,mode:this.state.controlMode||"manual"},tools:[
    {name:"list_commands",description:"列出游戏命令及参数定义",readOnly:true,inputSchema:object({category_id:string})},
    {name:"inspect_command",description:"查询单条命令的完整说明、分类、状态与参数约定；提交前先查不熟悉的命令",readOnly:true,inputSchema:object({command_id:string},["command_id"])},
    {name:"inspect_turn_reports",description:"按日查询本局战报/日报历史，包含实际下达命令与结算反馈；可查指定日期或按日期范围分页",readOnly:true,inputSchema:object({turn:{type:"integer"},from_turn:{type:"integer"},to_turn:{type:"integer"},limit:{type:"integer",minimum:1,maximum:30}})},
    {name:"inspect_city",description:"读取情报权限允许的城市资料",readOnly:true,inputSchema:object({city_id:string},["city_id"])},
    {name:"inspect_army",description:"读取情报权限允许的军团资料",readOnly:true,inputSchema:object({army_id:string},["army_id"])},
    {name:"inspect_officer",description:"读取情报权限允许的人物资料",readOnly:true,inputSchema:object({officer_id:string},["officer_id"])},
    {name:"inspect_relationships",description:"读取己方人物关系",readOnly:true,inputSchema:object({officer_id:string},["officer_id"])},
    {name:"inspect_economy",description:"读取势力经济情报",readOnly:true,inputSchema:object({force_id:string})},
    {name:"inspect_diplomacy",description:"读取公开外交关系",readOnly:true,inputSchema:object()},
    {name:"inspect_strategy",description:"读取受情报权限约束的天下形势、前线压力与敌军意图",readOnly:true,inputSchema:object()},
    {name:"inspect_war_plan",description:"评估已设置或指定城市的集结路线、补给和攻城风险",readOnly:true,inputSchema:object({city_id:string})},
    {name:"queue_war_plan",description:"把战争计划转换为集结或进攻命令并加入队列，不直接执行",readOnly:false,inputSchema:object({city_id:string,mode:{type:"string",enum:["stage","attack"]}})},
    {name:"inspect_defense_plan",description:"读取来袭城市、守军缺口、抵达时间和可用援军",readOnly:true,inputSchema:object()},
    {name:"queue_defense_plan",description:"把可及时抵达的驰援方案加入命令队列，不直接执行",readOnly:false,inputSchema:object()},
    {name:"get_pending_event",description:"读取当前待决事件",readOnly:true,inputSchema:object()},
    {name:"choose_event",description:"选择待决事件选项",readOnly:false,inputSchema:object({choice_id:string},["choice_id"])},
    {name:"submit_command",description:"把经过验证的命令加入本日队列，不直接修改世界状态",readOnly:false,inputSchema:object({command_id:string,actor_id:string,target_ids:{type:"array",items:string},amount:{type:"number"},options:{type:"object"}},["command_id","target_ids"])}
  ],commandCount:this.state.data.commandCatalog.commands.length};}
  call(name,args={},actor="player-ai"){
    const record={at:new Date().toISOString(),turn:this.state.turn,actor,name,args,status:"rejected"};let result;
    if(name==="list_commands"){result=this.state.data.commandCatalog.commands.filter(c=>!args.category_id||c.categoryId===args.category_id);record.status="ok"}
    else if(name==="inspect_command"){result=this.inspectCommand(args.command_id);record.status=result?"ok":"rejected"}
    else if(name==="inspect_turn_reports"){result=this.inspectTurnReports(args);record.status="ok"}
    else if(name==="inspect_city"){result=this.visibleCity(args.city_id);record.status=result?"ok":"rejected"}
    else if(name==="inspect_army"){result=this.visibleArmy(args.army_id);record.status=result?"ok":"rejected"}
    else if(name==="inspect_officer"){result=this.visibleOfficer(args.officer_id);record.status=result?"ok":"rejected"}
    else if(name==="inspect_relationships"){result=this.visibleRelationships(args.officer_id);record.status=result?"ok":"rejected"}
    else if(name==="inspect_economy"){result=this.visibleEconomy(args.force_id||this.state.playerForceId);record.status=result?"ok":"rejected"}
    else if(name==="inspect_diplomacy"){result=this.visibleDiplomacy();record.status="ok"}
    else if(name==="inspect_strategy"){result=this.state.engine.strategicIntel(this.state);record.status="ok"}
    else if(name==="inspect_war_plan"){result=this.state.engine.warPlan(this.state,args.city_id);record.status=result.target?"ok":"rejected"}
    else if(name==="queue_war_plan"){result=this.state.queueWarPlan(args.city_id||this.state.policies.militaryGoal,args.mode||"stage",actor);record.status=result.queued?.length?"queued":"rejected"}
    else if(name==="inspect_defense_plan"){result=this.state.engine.defensePlan(this.state);record.status="ok"}
    else if(name==="queue_defense_plan"){result=this.state.queueDefensePlan(actor);record.status=result.queued?.length?"queued":"rejected"}
    else if(name==="get_pending_event"){result=structuredClone(this.state.policies?.pendingEvent||null);record.status="ok"}
    else if(name==="choose_event"){result=this.chooseEvent(args.choice_id);record.status=result?.resolved?"ok":"rejected"}
    else if(name==="submit_command")result=this.submit(args,record);
    else result={error:"unknown_tool"};record.result=result;this.audit.push(record);return result;
  }
  chooseEvent(choiceId){const result=this.state.engine.resolveEventChoice(this.state,choiceId);if(!result)return {resolved:false,error:"no_pending_event_or_invalid_choice"};if(this.state.reports[0]){this.state.reports[0].events.push(result);this.state.reports[0].summary=`完成 ${this.state.reports[0].events.length} 项阶段结算。`}return {resolved:true,result};}
  inspectCommand(commandId){const command=this.state.data.commandCatalog.commands.find(item=>item.id===commandId);if(!command)return null;const rules={declare_war:"敌方城市需先对其所属势力宣战才能进入。",move:"只设置路线；旬末按路线推进，接敌或无法进入会中止并在日报记录原因。",forced_march:"比普通行军推进更快，但额外消耗补给并降低士气。",recruit_troops:"从势力金粮在指定己方城市增加守军；不会补充野战军团。",reinforce:"从军团当前驻地的己方可用守军转兵至指定军团；至少保留 1000 城市守军。",form_army:"从己方城市守军抽兵新建军团；不是征兵，需已有可用守军。",return_garrison:"将指定军团兵力转回其所在己方城市守军。"};return {...structuredClone(command),mechanics:rules[commandId]||command.description,source:"commandCatalog + engine rule notes"};}
  inspectTurnReports(args={}){const reports=this.state.reports||[],turn=Number.isInteger(args.turn)?args.turn:null,from=Number.isInteger(args.from_turn)?args.from_turn:-Infinity,to=Number.isInteger(args.to_turn)?args.to_turn:Infinity,limit=Math.max(1,Math.min(30,Number(args.limit)||5)),filtered=reports.filter(report=>turn!==null?report.turn===turn:report.turn>=from&&report.turn<=to),page=filtered.slice(0,limit).map(report=>({turn:report.turn,date:report.date,summary:report.summary,executed:(report.executed||[]).map(order=>({type:order.type,commandId:order.commandId,commandName:order.commandName,text:String(order.text||"").slice(0,180),actorId:order.actorId||order.issuer,targetIds:order.targetIds||[],amount:order.amount??null})),events:(report.events||[]).map(event=>({phase:event.phase||"",text:String(event.text||event).slice(0,240),result:event.result||null,battleId:event.battleId||null,armyId:event.armyId||null,cityId:event.cityId||event.siteId||null}))}));return {availableReports:reports.length,matched:filtered.length,returned:page.length,hasMore:filtered.length>page.length,reports:page};}
  submit(args,record){
    const command=this.state.data.commandCatalog.commands.find(c=>c.id===args.command_id);if(!command)return {queued:false,error:"unknown_command_id"};
    const rejected=error=>({queued:false,error,commandId:command.id,targetIds:args.target_ids||[]});
    const targetedArmy=(args.target_ids||[]).map(id=>this.state.data.armies.find(a=>a.id===id)).find(Boolean),targetedCity=(args.target_ids||[]).map(id=>this.state.data.cities.find(c=>c.id===id)).find(Boolean);
    if(targetedArmy&&targetedArmy.force!==this.state.playerForceId)return rejected("army_not_controlled");
    if(["agriculture","commerce","recruit_troops","form_army","construct_building"].includes(command.id)&&targetedCity?.force!==this.state.playerForceId)return rejected("city_not_controlled");
    if(command.id==="scout_city"&&targetedCity&&(this.state.intelligence?.cities?.[targetedCity.id]||0)>=3)return rejected("city_intelligence_already_maxed");
    if(command.id==="scout_army"&&targetedArmy&&(this.state.intelligence?.armies?.[targetedArmy.id]||0)>=3)return rejected("army_intelligence_already_maxed");
    if(["city_defense","fortify"].includes(command.id)&&targetedCity&&(targetedCity.level||1)>=5)return rejected("city_defense_already_maxed");
    if(["move","forced_march","redeploy","assemble"].includes(command.id)&&targetedCity&&![this.state.playerForceId,"neutral"].includes(targetedCity.force)&&!this.state.diplomacy.wars.includes(targetedCity.force)&&!this.state.orders.some(order=>order.type==="declare_war"&&order.forceIds?.includes(targetedCity.force)))return rejected(`must_declare_war_first:${targetedCity.force}`);
    const targetIds=args.target_ids||[],max=this.state.data.rules?.orders?.max_player_orders_per_turn||8;if(this.state.orders.length>=max)return rejected("order_limit_reached");const signature=`${command.id}:${[...targetIds].sort().join(",")}:${args.amount??""}:${JSON.stringify(args.options||{})}`;if(this.state.orders.some(order=>order.signature===signature))return rejected("duplicate_order");const names=targetIds.map(id=>this.resolveName(id)).filter(Boolean),amount=args.amount?` ${args.amount}`:"",text=`${command.categoryName}/${command.name}${names.length?` ${names.join(" 至 ")}`:""}${amount}`,order=this.state.addStructuredOrder(command.id,{text,actorId:args.actor_id||"player-ai",targetIds,cityIds:targetIds.filter(id=>this.state.data.cities.some(c=>c.id===id)),armyIds:targetIds.filter(id=>this.state.data.armies.some(a=>a.id===id)),officerIds:targetIds.filter(id=>this.state.data.officers.some(o=>o.id===id)),forceIds:targetIds.filter(id=>this.state.data.forces.some(f=>f.id===id)),itemIds:targetIds.filter(id=>this.state.data.items?.some(i=>i.id===id)),amount:args.amount,options:args.options||{}});if(!order)return rejected("order_invalid");record.status="queued";return {queued:true,orderId:order.id,commandId:command.id,status:command.status,text};
  }
  resolveName(id){return this.state.data.cities.find(v=>v.id===id)?.name||this.state.data.armies.find(v=>v.id===id)?.name||this.state.data.officers.find(v=>v.id===id)?.name||this.state.data.forces.find(v=>v.id===id)?.name||this.state.data.items?.find(v=>v.id===id)?.name||this.state.corps.find(v=>v.id===id)?.name;}
  visibleArmy(id){const army=this.state.data.armies.find(a=>a.id===id);if(!army)return null;if(army.force===this.state.playerForceId)return {...structuredClone(army),combat:this.state.engine.combatBreakdown(army)};const level=this.state.intelligence.armies[id]||0;if(!level)return null;const view={id:army.id,name:army.name,force:army.force,city:army.city,intelligenceLevel:level,intelligenceAtMaximum:level>=3,soldiersEstimate:`约 ${Math.max(1,Math.round(army.soldiers/5000)*5)}K`};if(level>=2)Object.assign(view,{commander:army.commander,soldiers:army.soldiers,stance:army.stance,siegeTarget:army.siegeTarget});if(level>=3)Object.assign(view,{units:army.units,training:army.training,morale:army.morale,supply:army.supply,route:army.route,destination:army.destination,combat:this.state.engine.combatBreakdown(army)});return view;}
  visibleCity(id){const city=this.state.data.cities.find(c=>c.id===id);if(!city)return null;if(city.force===this.state.playerForceId)return {...structuredClone(city),defenseAtMaximum:(city.level||1)>=5};const level=this.state.intelligence.cities[id]||0,view={id:city.id,name:city.name,force:city.force,province:city.province,type:city.type||"city",intelligenceLevel:level,intelligenceAtMaximum:level>=3};if(level>=1)Object.assign(view,{populationEstimate:`约 ${Math.max(1,Math.round(city.population/50000)*5)}万`,garrisonEstimate:`约 ${Math.max(1,Math.round(city.garrison/5000)*5)}千`,underSiege:Boolean(city.siegeTurns)});if(level>=2)Object.assign(view,{population:city.population,garrison:city.garrison,governor:city.governor,level:city.level,defenseIntegrity:Math.max(0,100-(city.defenseDamage||0)),siegeTurns:city.siegeTurns||0});if(level>=3)Object.assign(view,{commerce:city.commerce,agriculture:city.agriculture,order:city.order,localGold:city.localGold,localFood:city.localFood,buildings:city.buildings});return view;}
  visibleOfficer(id){const officer=this.state.data.officers.find(o=>o.id===id);if(!officer)return null;if(officer.force===this.state.playerForceId||officer.capturedBy===this.state.playerForceId||["free","discovered"].includes(officer.status))return structuredClone(officer);const level=this.state.intelligence.officers[id]||0;if(!level)return null;const view={id:officer.id,name:officer.name,force:officer.force,intelligenceLevel:level};if(level>=1)Object.assign(view,{city:officer.city,status:officer.status});if(level>=2)Object.assign(view,{command:officer.command,war:officer.war,intelligence:officer.intelligence,politics:officer.politics,injuredUntil:officer.injuredUntil});if(level>=3)Object.assign(view,{charm:officer.charm,loyalty:officer.loyalty,skill:officer.skill,aptitude:officer.aptitude,office:officer.office});return view;}
  visibleRelationships(id){const officer=this.state.data.officers.find(o=>o.id===id);if(!officer||officer.force!==this.state.playerForceId)return null;const bonds=Object.entries(this.state.personalRelations||{}).filter(([key])=>key.split(":").includes(id)).map(([key,value])=>({officerId:key.split(":").find(x=>x!==id),value}));return {officerId:id,personality:officer.personality,faction:officer.faction,ambition:officer.ambition,loyalty:officer.loyalty,swornWith:officer.swornWith||null,spouse:officer.spouse||null,recommendedBy:officer.recommendedBy||null,bonds};}
  visibleEconomy(forceId){const force=this.state.data.forces.find(f=>f.id===forceId);if(!force)return null;const cities=this.state.data.cities.filter(c=>c.force===forceId);if(forceId===this.state.playerForceId)return {forceId,gold:this.state.resources.gold,food:this.state.resources.food,silk:this.state.resources.silk,units:{gold:"贯",food:"石",silk:"品",labor:"人日"},fiscal:{account:structuredClone(this.state.policies.fiscalAccounts?.forces[forceId]),shipments:(this.state.policies.fiscalAccounts?.shipments||[]).filter(cargo=>cargo.forceId===forceId),laborGroups:(this.state.policies.fiscalAccounts?.laborGroups||[]).filter(group=>group.forceId===forceId),projects:(this.state.policies.fiscalAccounts?.projects||[]).filter(project=>project.forceId===forceId)},armyStores:this.state.data.armies.filter(army=>army.force===forceId).map(army=>({id:army.id,stores:army.stores})),grainPrice:this.state.engine.grainPrice(this.state),cities:cities.map(c=>({id:c.id,localGold:c.localGold,localFood:c.localFood,localSilk:c.localSilk,publicSupport:c.publicSupport,fiscal:c.fiscal,storage:c.storage,reserveRatio:c.reserveRatio,supply:this.state.engine.citySupplyStatus(this.state,c.id,forceId)})),supplyRoutes:(this.state.infrastructure.supplyRoutes||[]).map(key=>this.state.engine.assessSupplyRoute(this.state,key,forceId)),history:(this.state.policies.economyHistory||[]).slice(-12)};const intel=cities.reduce((n,c)=>n+(this.state.intelligence.cities[c.id]||0),0);if(!intel)return null;return {forceId,cityCount:cities.length,goldEstimate:`约 ${Math.round((force.resources?.gold||0)/5000)*5}K`,foodEstimate:`约 ${Math.round((force.resources?.food||0)/5000)*5}K`};}
  visibleDiplomacy(){const forces=this.state.data.forces.filter(f=>f.id!=="neutral"&&!f.eliminated),relations=[];for(let i=0;i<forces.length;i++)for(let j=i+1;j<forces.length;j++){const a=forces[i],b=forces[j],key=this.state.engine.pairKey(a.id,b.id),world=this.state.diplomacy.worldTreaties?.find(t=>t.key===key),other=a.id===this.state.playerForceId?b.id:b.id===this.state.playerForceId?a.id:null,legacy=other?this.state.diplomacy.treaties.find(t=>t.forceId===other):null;relations.push({a:a.id,b:b.id,relation:this.state.engine.worldRelation(this.state,a.id,b.id),status:this.state.engine.worldWar(this.state,a.id,b.id)?"war":(legacy||world)?.type||"neutral",vassalOf:this.state.diplomacy.worldVassals?.[a.id]||this.state.diplomacy.worldVassals?.[b.id]||null})}return {relations,coalitions:structuredClone(this.state.diplomacy.coalitions||[])};}
};
