window.GameState = class GameState extends EventTarget {
  static SAVE_VERSION=16;
  constructor(data,options={}){
    super();this.data=data;this.playerForceId=options.playerForceId||data.scenario?.player_force||"cao";this.observerMode=options.observerMode??this.playerForceId==="observer";this.observerDelay=Number(options.observerDelay)||3000;this.difficulty=options.difficulty||"normal";
    for(const city of data.cities)this.hydrateCity(city);for(const county of data.counties||[])this.hydrateCounty(county);for(const officer of data.officers)this.hydrateOfficer(officer);
    this.engine=new RuleEngine(data);for(const army of data.armies)this.hydrateArmy(army);this.engine.syncAllArmyOfficerLocations();this.turn=1;const [year,month]=String(data.scenario?.start_date||"200-01-01").split("-").map(Number);this.date={year,month,xun:0};this.layer="terrain";this.orders=[];this.reports=[];this.chronicles=[];this.worldChronicles=[];this.resources={gold:12480,food:38600,prestige:276};this.relations=Object.fromEntries(data.forces.filter(f=>![this.playerForceId,"neutral"].includes(f.id)).map(f=>[f.id,0]));this.personalRelations={};this.diplomacy={wars:[],treaties:[],vassals:{},worldRelations:{},worldWars:[],worldTreaties:[],worldVassals:{},coalitions:[]};this.intelligence={cities:{},armies:{},officers:{},routes:{},terrain:{},counter:0};this.policies={taxRate:10,development:"均衡",militaryGoal:null,diplomatic:"中立",fiscal:"稳健",authority:"逐项审批"};this.technology={points:0,administration:0,levels:{agriculture:0,military:0,logistics:0,administration:0}};this.corps=[];this.infrastructure={supplyRoutes:[],routeStatuses:{}};this.advisorOfficerId=null;this.heirOfficerId=null;this.rngState=20000101;this.selected={type:"city",value:data.cities.find(c=>c.force===this.playerForceId)||data.cities[0]};
  }
  hydrateCity(city){city.localGold??=Math.round(city.population/20);city.localFood??=Math.round(city.population/8);city.storage??=20000;city.localFood=Math.min(city.storage,city.localFood);city.labor??=0;city.buildings??=[];city.defenseDamage??=0;city.reserveRatio??=25;city.siegeMorale??=Math.max(35,Math.min(100,city.order??72));city.commandery??=city.historical?.commandery||"史籍未详";city.counties??=[city.name];city.administration??={};city.administration.progress??={};city.administration.boosts??={};city.administration.recruitmentTarget??=Math.max(city.garrison||0,(city.garrison||0)+(city.level||1)*500);city.administration.trainingTarget??=80}
  hydrateCounty(county){const city=this.data.cities.find(item=>item.id===county.jurisdictionCityId);county.force??=city?.force||"neutral";county.population=Math.max(100,Math.round(county.population||county.historicalPopulation*.32||500));county.agriculture??=city?.agriculture||40;county.commerce??=city?.commerce||35;county.order??=city?.order||60;county.developmentProgress??={};for(const key of ["agriculture","commerce","order"])county.developmentProgress[key]??=0;county.lastIncome??={gold:0,food:0}}
  hydrateOfficer(officer){officer.stamina??=100;officer.experience??=0;officer.skills??=[];const ranked=[["果决",officer.war||0],["统御",officer.command||0],["谋略",officer.intelligence||0],["经世",officer.politics||0],["仁厚",officer.charm||0]].sort((a,b)=>b[1]-a[1]);officer.personality??=ranked[0][0];officer.ambition??=Math.max(1,Math.min(5,Math.round(((officer.war||50)+(officer.intelligence||50)+(100-(officer.loyalty??70)))/60)));officer.faction??=officer.personality==="果决"||officer.personality==="统御"?"武略派":officer.personality==="经世"?"文治派":officer.personality==="谋略"?"谋臣派":"名望派"}
  hydrateArmy(army){army.supply??=100;army.morale??=70;army.training??=50;army.valor??=50;army.reinforcementTarget??=army.soldiers||0;army.deputyOfficerIds??=[];army.staffOfficerId??=null;this.engine?.configureDoctrine(army)}
  migrateSave(input){const save=structuredClone(input),from=Number(save.version||1);if(from<1||from>GameState.SAVE_VERSION)throw new Error(`存档版本 ${from} 不受支持`);save.orders??=[];save.reports??=[];save.chronicles??=[];save.worldChronicles??=[];save.resources??={gold:12480,food:38600,prestige:276};save.relations??={};save.personalRelations??={};save.diplomacy??={};Object.assign(save.diplomacy,{wars:save.diplomacy.wars||[],treaties:save.diplomacy.treaties||[],vassals:save.diplomacy.vassals||{},worldRelations:save.diplomacy.worldRelations||{},worldWars:save.diplomacy.worldWars||[],worldTreaties:save.diplomacy.worldTreaties||[],worldVassals:save.diplomacy.worldVassals||{},coalitions:save.diplomacy.coalitions||[]});save.intelligence??={};for(const key of ["cities","armies","officers","routes","terrain"])save.intelligence[key]??={};save.intelligence.counter??=0;save.policies={taxRate:10,development:"均衡",militaryGoal:null,diplomatic:"中立",fiscal:"稳健",authority:"逐项审批",aiMemory:[],...(save.policies||{})};save.policies.aiMemory??=[];save.technology??={};save.technology.points??=0;save.technology.administration??=0;save.technology.levels={agriculture:0,military:0,logistics:0,administration:save.technology.administration||0,...(save.technology.levels||{})};save.corps??=[];save.infrastructure??={};save.infrastructure.supplyRoutes??=[];save.infrastructure.routeStatuses??={};save.rngState??=20000101;save.migratedFrom=from;save.version=GameState.SAVE_VERSION;return save}
  updateOfficerLifecycle(){for(const officer of this.data.officers){if(officer.status==="dead")continue;if(officer.injuredUntil&&this.turn>=officer.injuredUntil){delete officer.injuredUntil;if(officer.status==="injured")officer.status="serving";officer.stamina=Math.max(60,officer.stamina||0)}if(officer.deathYear&&this.date.year>officer.deathYear){officer.status="dead";officer.force="neutral";continue}if(officer.status==="not_appeared"&&officer.debutYear&&this.date.year>=officer.debutYear){officer.status="hidden";officer.force="neutral"}}this.engine.syncAllArmyOfficerLocations()}
  emit(type,detail={}){this.dispatchEvent(new CustomEvent(type,{detail}))}
  setLayer(layer){this.layer=layer;this.emit("layer",{layer})}
  select(type,value){this.selected={type,value};this.emit("selection",this.selected)}
  addOrder(text,issuer="player"){const clean=text.trim(),max=this.data.rules?.orders?.max_player_orders_per_turn||8;if(!clean){this.emit("orderRejected",{reason:"命令内容为空"});return false}if(this.orders.length>=max){this.emit("orderRejected",{reason:`本旬命令已达上限（${max}）`});return false}this.orders.push(this.engine.parse(clean,this.turn));this.emit("orders",{reason:"queued"});return true}
  addStructuredOrder(commandId,payload={}){const command=this.data.commandCatalog.commands.find(item=>item.id===commandId);if(!command)return null;const targetIds=payload.targetIds||[],signature=`${commandId}:${[...targetIds].sort().join(",")}:${payload.amount??""}:${JSON.stringify(payload.options||{})}`;if(this.orders.some(order=>order.signature===signature)){this.emit("orderRejected",{reason:"相同命令已在本旬队列中"});return null}const actingOfficer=["relationship","personal"].includes(command.categoryId)?payload.officerIds?.[0]:null;if(actingOfficer&&this.orders.some(order=>order.actingOfficer===actingOfficer)){this.emit("orderRejected",{reason:"该人物本旬已安排了行动"});return null}const names=targetIds.map(id=>[...this.data.cities,...this.data.armies,...this.data.officers,...this.data.forces].find(item=>item.id===id)?.name).filter(Boolean),text=payload.text||`${command.categoryName}/${command.name}${names.length?` ${names.join(" 至 ")}`:""}${payload.amount?` ${payload.amount}`:""}`;if(!this.addOrder(text,payload.actorId||"player"))return null;const order=this.orders.at(-1);Object.assign(order,{issuer:payload.actorId||"player",actorId:payload.actorId||"player",type:command.id,commandId:command.id,commandName:command.name,categoryId:command.categoryId,categoryName:command.categoryName,status:command.status,signature,actingOfficer,targetIds,cityIds:payload.cityIds||[],armyIds:payload.armyIds||[],officerIds:payload.officerIds||[],forceIds:payload.forceIds||[],itemIds:payload.itemIds||[],amount:payload.amount??order.amount,options:payload.options||{}});this.emit("orders",{reason:"updated"});return order}
  removeOrder(id){this.orders=this.orders.filter(order=>order.id!==id);this.emit("orders",{reason:"removed"})}
  clearOrders(){this.orders=[];this.emit("orders",{reason:"cleared"})}
  queueWarPlan(targetId=this.policies.militaryGoal,mode="stage",actorId="player"){const prepared=this.engine.warPlanOrders(this,targetId,mode),max=this.data.rules?.orders?.max_player_orders_per_turn||8,room=Math.max(0,max-this.orders.length),queued=[];if(prepared.errors.length&&(mode==="attack"&&!prepared.atWar))return {...prepared,queued,skipped:prepared.proposals.length};for(const proposal of prepared.proposals.slice(0,room)){const order=this.addStructuredOrder(proposal.commandId,{text:proposal.text,actorId,armyIds:[proposal.armyId],cityIds:[proposal.cityId],targetIds:[proposal.armyId,proposal.cityId],options:{route:proposal.route,warPlanMode:mode,warPlanTargetId:targetId}});if(order)queued.push(order.id)}return {...prepared,queued,skipped:Math.max(0,prepared.proposals.length-queued.length),capacity:room}}
  queueDefensePlan(actorId="player"){const prepared=this.engine.defenseOrders(this),max=this.data.rules?.orders?.max_player_orders_per_turn||8,room=Math.max(0,max-this.orders.length),queued=[];for(const proposal of prepared.proposals.slice(0,room)){const order=this.addStructuredOrder(proposal.commandId,{text:proposal.text,actorId,armyIds:[proposal.armyId],cityIds:[proposal.cityId],targetIds:[proposal.armyId,proposal.cityId],options:{route:proposal.route,defensePlan:true,reason:proposal.reason}});if(order)queued.push(order.id)}return {...prepared,queued,skipped:Math.max(0,prepared.proposals.length-queued.length),capacity:room}}
  economicSnapshot(){const cities=this.data.cities.filter(city=>city.force===this.playerForceId),counties=(this.data.counties||[]).filter(county=>cities.some(city=>city.id===county.jurisdictionCityId)),armies=this.data.armies.filter(army=>army.force===this.playerForceId);return {gold:this.resources.gold||0,food:this.resources.food||0,prestige:this.resources.prestige||0,population:cities.reduce((sum,city)=>sum+(city.population||0),0)+counties.reduce((sum,county)=>sum+(county.population||0),0),soldiers:cities.reduce((sum,city)=>sum+(city.garrison||0),0)+armies.reduce((sum,army)=>sum+(army.soldiers||0),0),localGold:cities.reduce((sum,city)=>sum+(city.localGold||0),0),localFood:cities.reduce((sum,city)=>sum+(city.localFood||0),0)}}
  endTurn(){const executed=this.orders.slice(),label=this.dateLabel,before=this.economicSnapshot(),events=this.engine.resolve(this,executed),after=this.economicSnapshot(),resourceDelta=Object.fromEntries(Object.keys(before).map(key=>[key,after[key]-before[key]]));this.reports.unshift({turn:this.turn,date:label,executed,events,resourceDelta,summary:`完成 ${events.length} 项阶段结算。`});this.orders=[];this.turn+=1;this.date.xun+=1;if(this.date.xun===3){this.date.xun=0;this.date.month+=1}if(this.date.month===13){this.date.month=1;this.date.year+=1}this.updateOfficerLifecycle();this.emit("turn",{executed,events,resourceDelta});this.emit("orders",{reason:"settled"});if(!this.observerMode&&typeof localStorage!=="undefined"&&typeof localStorage.getItem==="function")this.save("auto",this.saveSlot||"1");return events}
  random(){let x=this.rngState|0;x^=x<<13;x^=x>>>17;x^=x<<5;this.rngState=x>>>0;return this.rngState/4294967296}
  serialize(){return {version:GameState.SAVE_VERSION,savedAt:new Date().toISOString(),scenarioId:this.data.scenario?.id||"200_guandu",playerForceId:this.playerForceId,observerMode:this.observerMode,observerDelay:this.observerDelay,difficulty:this.difficulty||"normal",controlMode:this.controlMode||"manual",gameOver:this.gameOver||null,turn:this.turn,date:this.date,orders:this.orders,reports:this.reports,chronicles:this.chronicles||[],worldChronicles:this.worldChronicles||[],resources:this.resources,relations:this.relations,personalRelations:this.personalRelations,diplomacy:this.diplomacy,intelligence:this.intelligence,policies:this.policies,technology:this.technology,corps:this.corps,infrastructure:this.infrastructure,advisorOfficerId:this.advisorOfficerId,heirOfficerId:this.heirOfficerId,rngState:this.rngState,world:{cities:this.data.cities,counties:this.data.counties,armies:this.data.armies,officers:this.data.officers,items:this.data.items,forces:this.data.forces,cityGraph:this.data.rules.city_graph},layer:this.layer,selected:{type:this.selected.type,id:this.selected.value.id,countyId:this.selected.value.county?.id,x:this.selected.value.x,y:this.selected.value.y}}}
  save(kind="manual",slot="1"){const id=String(slot),key=`sanguo-cli.slot.${id}`,snapshot=this.serialize(),raw=JSON.stringify(snapshot),previous=localStorage.getItem(key),meta={kind,slot:id,scenarioId:this.data.scenario?.id||"200_guandu",forceId:this.playerForceId,turn:this.turn,dateLabel:this.dateLabel,savedAt:snapshot.savedAt},hosted=typeof location!=="undefined"&&/^https?:$/.test(location.protocol||"");this.saveSlot=id;let localSaved=false;try{if(!hosted&&previous)localStorage.setItem(`${key}.backup`,previous);localStorage.setItem(key,raw);localSaved=true;try{localStorage.setItem(`${key}.meta`,JSON.stringify(meta))}catch{}if(hosted){localStorage.removeItem?.(`${key}.backup`);if(id==="1"){localStorage.removeItem?.("sanguo-cli.save.v1");localStorage.removeItem?.("sanguo-cli.save.v1.meta")}}else if(id==="1"){try{localStorage.setItem("sanguo-cli.save.v1",raw);localStorage.setItem("sanguo-cli.save.v1.meta",JSON.stringify({kind,turn:this.turn,savedAt:snapshot.savedAt}))}catch{}}}catch(error){this.persistenceWarning=/quota|配额/i.test(String(error?.message||error))?"浏览器存储空间已满，进度已转存到本地游戏服务。":`浏览器存档写入失败：${error.message||error}`;for(const stale of [`${key}.backup`,"sanguo-cli.save.v1","sanguo-cli.save.v1.meta"])try{localStorage.removeItem?.(stale)}catch{}try{localStorage.setItem(key,raw);localSaved=true}catch{}}this.queueHostSave(id,snapshot,meta);return localSaved||hosted}
  queueHostSave(slot,save,meta){if(typeof fetch!=="function"||typeof location==="undefined"||!/^https?:$/.test(location.protocol||""))return;const prior=this.pendingHostSave||Promise.resolve();this.pendingHostSave=prior.catch(()=>false).then(()=>fetch(`/api/saves/${slot}`,{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({save,meta})}).then(response=>response.ok).catch(()=>false))}
  async flushPersistence(){return this.pendingHostSave?this.pendingHostSave:true}
  loadSafely(slot="1"){const id=String(slot),key=`sanguo-cli.slot.${id}`,legacy=id==="1"?"sanguo-cli.save.v1":null,candidates=[[key,false],[`${key}.backup`,true],...(legacy?[[legacy,false],[`${legacy}.backup`,true]]:[])];let lastError=null;for(const [candidate,recovered] of candidates){const raw=localStorage.getItem(candidate);if(!raw)continue;try{const parsed=this.migrateSave(JSON.parse(raw));if(parsed.scenarioId&&parsed.scenarioId!==this.data.scenario?.id)throw new Error(`存档属于剧本 ${parsed.scenarioId}`);if(recovered)try{localStorage.setItem(key,raw)}catch{}const loaded=this.applySave(parsed,id);this.lastRecovery={recovered,source:candidate};return loaded}catch(error){lastError=error}}if(lastError)throw new Error(`存档及备份均无法读取：${lastError.message}`);return false}
  restoreWorld(world={}){
    this.baseWorldMap??={cities:structuredClone(this.data.cities),counties:structuredClone(this.data.counties||[]),officers:structuredClone(this.data.officers||[]),cityGraph:structuredClone(this.data.rules.city_graph||{})};
    const savedCities=new Map((world.cities||[]).map(city=>[city.id,city])),baseIds=new Set(this.baseWorldMap.cities.map(city=>city.id));
    this.data.cities=this.baseWorldMap.cities.map(base=>{const saved=savedCities.get(base.id);return saved?{...structuredClone(base),...saved,name:base.name,type:base.type,x:base.x,y:base.y,province:base.province}:structuredClone(base)});
    for(const city of world.cities||[])if(!baseIds.has(city.id))this.data.cities.push(city);
    const savedCounties=new Map((world.counties||[]).map(county=>[county.id,county]));this.data.counties=this.baseWorldMap.counties.map(base=>{const saved=savedCounties.get(base.id);return saved?{...structuredClone(base),...saved,id:base.id,name:base.name,commandery:base.commandery,x:base.x,y:base.y,cityId:base.cityId,jurisdictionCityId:base.jurisdictionCityId,historicalPopulation:base.historicalPopulation,censusYear:base.censusYear,rank:base.rank}:structuredClone(base)});
    if(world.armies)this.data.armies=world.armies;if(world.officers){const savedOfficers=new Map(world.officers.map(officer=>[officer.id,officer])),baseOfficerIds=new Set(this.baseWorldMap.officers.map(officer=>officer.id));this.data.officers=this.baseWorldMap.officers.map(base=>{const saved=savedOfficers.get(base.id);return saved?{...structuredClone(base),...saved,id:base.id,name:base.name,sourceId:base.sourceId}:structuredClone(base)});for(const saved of world.officers)if(!baseOfficerIds.has(saved.id))this.data.officers.push(saved)}if(world.items)this.data.items=world.items;if(world.forces)this.data.forces=world.forces;
    const cityIds=new Set(this.data.cities.map(city=>city.id)),savedGraph=world.cityGraph||{},keys=new Set([...Object.keys(this.baseWorldMap.cityGraph),...Object.keys(savedGraph)]),graph={};
    for(const id of keys)if(cityIds.has(id))graph[id]=[...new Set([...(this.baseWorldMap.cityGraph[id]||[]),...(savedGraph[id]||[])])].filter(next=>cityIds.has(next));
    this.data.rules.city_graph=graph;
  }
  load(slot="1"){
    const id=String(slot),key=`sanguo-cli.slot.${id}`,raw=localStorage.getItem(key)||(id==="1"?localStorage.getItem("sanguo-cli.save.v1"):null);if(!raw)return false;return this.applySave(this.migrateSave(JSON.parse(raw)),id)
  }
  applySave(save,id="1"){
    this.saveSlot=id;this.playerForceId=save.playerForceId||this.playerForceId;this.observerMode=!!save.observerMode;this.observerDelay=save.observerDelay||3000;this.difficulty=save.difficulty||"normal";this.controlMode=save.controlMode||"manual";this.gameOver=save.gameOver||null;this.turn=save.turn;this.date=save.date;this.orders=save.orders;this.reports=save.reports;this.chronicles=save.chronicles||[];this.worldChronicles=save.worldChronicles||[];this.resources=save.resources;this.relations=save.relations;this.personalRelations=save.personalRelations;this.diplomacy=save.diplomacy;this.intelligence=save.intelligence;this.policies=save.policies;this.technology=save.technology;this.corps=save.corps;this.infrastructure=save.infrastructure;this.advisorOfficerId=save.advisorOfficerId||null;this.heirOfficerId=save.heirOfficerId||null;this.rngState=save.rngState;
    this.restoreWorld(save.world);for(const city of this.data.cities)this.hydrateCity(city);for(const county of this.data.counties||[])this.hydrateCounty(county);for(const officer of this.data.officers)this.hydrateOfficer(officer);for(const army of this.data.armies)this.hydrateArmy(army);this.engine.syncAllArmyOfficerLocations();this.layer=save.layer||"terrain";
    const ref=save.selected||{},county=this.data.counties?.find(item=>item.id===ref.countyId);this.selected=ref.type==="city"?{type:"city",value:this.data.cities.find(c=>c.id===ref.id)||this.data.cities[0]}:{type:"cell",value:{x:ref.x||0,y:ref.y||0,terrain:"plains",province:county?.province||"豫州",commandery:county?.commandery||null,county:county||null,supply:5}};this.lastMigration={from:save.migratedFrom,to:save.version};this.emit("restore");this.emit("orders",{reason:"restored"});this.emit("layer",{layer:this.layer});this.emit("selection",this.selected);return true;
  }
  get dateLabel(){return `${this.date.year}年 ${this.date.month}月 ${["上旬","中旬","下旬"][this.date.xun]}`}
};
