window.FiscalUI=class FiscalUI {
  static esc(value){return String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[char])}
  static number(value){return Number(value||0).toLocaleString()}
  static cityMarkup(state,city){
    if(city.force!==state.playerForceId)return "";
    const g=FiscalSystem.governance(state,city),n=value=>this.number(value);
    return `<section class="biography"><h3>地方财政</h3><div class="data-row"><span>地方钱币／粮食／布帛</span><b>${n(city.localGold)}贯 · ${n(city.localFood)}石 · ${n(city.localSilk)}品</b></div><div class="data-row"><span>政府效率／贪污度</span><b>${Math.round(g.efficiency*100)}%／${Math.round(g.corruption*100)}%</b></div><div class="data-row"><span>民心／官员注意力占用</span><b>${Math.round(city.publicSupport)}／${Math.round(city.fiscal.attention)}</b></div><button type="button" data-city-fiscal>查看征收与上缴明细</button></section>`;
  }
  static armyMarkup(state,army){
    const city=FiscalSystem.stationedCity(state,army);
    return `<section class="biography"><h3>军队仓储</h3><div class="data-row"><span>钱币／粮食／布帛</span><b>${this.number(army.stores?.gold)}贯 · ${this.number(army.stores?.food)}石 · ${this.number(army.stores?.silk)}品</b></div><div class="data-row"><span>每日军粮</span><b>${this.number(FiscalSystem.armyDailyNeed(state,army))}石 · 随军满仓 ${this.number(FiscalSystem.armyFoodTarget(state,army))}石</b></div><div class="data-row"><span>就食来源</span><b>${city?`驻${this.esc(city.name)}：优先消耗城市粮仓，军仓兜底`:"随军军仓：行军、围城或无城可就食"}</b></div></section>`;
  }
  static rationMarkup(state,army){
    const city=FiscalSystem.stationedCity(state,army),stores=this.number(army.stores?.food);
    if(city)return `<b>城市粮仓</b><small>${this.esc(city.name)} · 军仓 ${stores}／${this.number(FiscalSystem.armyFoodTarget(state,army))}石</small>`;
    const reason=army.siegeTarget?"围城":army.route?.length?"行军":"无城可就食";
    return `<b>随军军仓</b><small>${reason} · 存粮 ${stores}石</small>`;
  }
  static palette=["#c8a84b","#6eaa79","#a8745c","#7f92b8","#b98fb0","#8ba35f","#c07f5f","#5f9ea0","#9a8f5f","#8f7fb8"];
  static kindLabels={land:"田租",commercial:"商税",food:"秋粮",silk:"布帛"};
  static sourceMarkup(state){
    const cities=state.data.cities.filter(city=>city.force===state.playerForceId),account=FiscalSystem.account(state),colorOf=cityId=>this.palette[Math.max(0,cities.findIndex(city=>city.id===cityId))%this.palette.length],resources=[["gold","钱币"],["food","粮食"],["silk","布帛"]],e=value=>this.esc(value),n=value=>this.number(value);
    const sources=FiscalSystem.incomeSources(state).filter(source=>source.total>0),arrears=FiscalSystem.pendingArrears(state),keptTotals=cities.reduce((totals,city)=>{const kept=city.fiscal?.arrearsRetained;if(kept)for(const key of ["gold","food","silk"])totals[key]+=kept[key]||0;return totals},{gold:0,food:0,silk:0}),resourceLine=totals=>["gold","food","silk"].filter(key=>totals[key]>0).map(key=>`${FiscalSystem.names[key]} ${n(totals[key])}${FiscalSystem.units[key]}`).join(" · ");
    const arrearsStatus=[resourceLine(arrears)?`待补缴 ${resourceLine(arrears)}`:"",resourceLine(keptTotals)?`累计转地方留用 ${resourceLine(keptTotals)}`:""].filter(Boolean).join("；")||"当前没有欠缴";
    const arrearsRow=`<div class="fiscal-arrears"><span>欠缴处理：${e(FiscalSystem.arrearsModes[account.arrears])}</span><b>${arrearsStatus}</b><button type="button" data-arrears-toggle data-tip="${account.arrears==="retain"?"欠额恢复追缴至首都":"欠额不再补缴，转入地方留用"}">${account.arrears==="retain"?"改为补缴至首都":"改为地方留用"}</button></div>`;
    if(!sources.length)return `<details open><summary>收入来源</summary><p class="briefing-empty">尚无征收记录：推进到月末征收或九月秋收后，这里按郡县列出上一次收入与占比。</p>${arrearsRow}</details>`;
    const cards=sources.map(source=>{const [,name]=resources.find(([key])=>key===source.resource),unit=FiscalSystem.units[source.resource];
      const bar=source.entries.map(entry=>`<i style="width:${(entry.share*100).toFixed(1)}%;background:${colorOf(entry.cityId)}" data-tip="${e(entry.cityName)} ${n(entry.gross)}${unit} · ${Math.round(entry.share*100)}%"></i>`).join('');
      const legend=source.entries.map(entry=>{const detail=[entry.kinds.map(kind=>this.kindLabels[kind]).join("＋"),entry.remitted?`上缴 ${n(entry.remitted)}${unit}`:"",entry.retained?`留用 ${n(entry.retained)}${unit}`:"",entry.arrears?`欠缴 ${n(entry.arrears)}${unit}`:""].filter(Boolean).join(" · ");
        return `<li><i style="background:${colorOf(entry.cityId)}"></i><b>${e(entry.cityName)}</b><small>${n(entry.gross)}${unit} · ${Math.round(entry.share*100)}%</small><em>${e(detail)}</em></li>`}).join('');
      return `<section class="fiscal-source-card"><header><b>${name}／${unit}</b><small>最近一次征收 · 第 ${source.turn} 日 · 合计 ${n(source.total)}${unit}</small></header><div class="fiscal-source-bar">${bar}</div><ul class="fiscal-source-legend">${legend}</ul></section>`}).join('');
    return `<details open><summary>收入来源（按郡县占比）</summary><div class="fiscal-source">${cards}</div>${arrearsRow}</details>`;
  }
  static markup(state){
    const ledger=FiscalSystem.initialize(state),account=FiscalSystem.account(state),cities=state.data.cities.filter(city=>city.force===state.playerForceId),army=state.data.armies.filter(army=>army.force===state.playerForceId),capital=state.data.cities.find(city=>city.id===account.capitalId),n=value=>this.number(value),e=value=>this.esc(value),sum=(items,key)=>items.reduce((total,item)=>total+(item[key]||0),0);
    const deliveries=ledger.shipments.filter(cargo=>cargo.forceId===state.playerForceId&&!['完成','没收'].includes(cargo.status));
    const resources=[['gold','钱币','贯'],['food','粮食','石'],['silk','布帛','品']];
    const summary=resources.map(([key,name,unit])=>`<tr><th>${name}／${unit}</th><td>${n(state.resources[key])}</td><td>${n(sum(cities,{gold:'localGold',food:'localFood',silk:'localSilk'}[key]))}</td><td>${n(army.reduce((total,army)=>total+(army.stores?.[key]||0),0))}</td><td>${n(deliveries.filter(cargo=>cargo.resource===key).reduce((total,cargo)=>total+cargo.delivered,0))}</td></tr>`).join('');
    const rows=cities.map(city=>{const g=FiscalSystem.governance(state,city),f=city.fiscal;return `<tr><td><b>${e(city.name)}</b></td><td>${n(city.localGold)}贯<br>${n(city.localFood)}石<br>${n(city.localSilk)}品</td><td>${Math.round(g.efficiency*100)}%／${Math.round(g.corruption*100)}%<small>民心 ${Math.round(city.publicSupport)} · 注意力占用 ${Math.round(f.attention)}</small></td><td>田租 ${n(f.accrued.land)}贯<br>商税 ${n(f.accrued.commercial)}贯<br>秋粮 ${n(f.accrued.food)}石<br>布帛 ${n(f.accrued.silk)}品</td><td>${Object.entries(f.lastCollection||{}).map(([kind,item])=>`<details><summary>${{land:'田租',commercial:'商税',food:'秋粮',silk:'布帛'}[kind]} ${n(item.gross)}${FiscalSystem.units[item.resource]}</summary><p>征收经费 ${item.cost}贯；行政损耗 ${item.inefficiencyLoss}；贪污 ${item.corruptionLoss}；地方耗用 ${item.localUse}；留用 ${item.retained}；在途上缴 ${item.remitted}；路损 ${item.transportLoss}；预计入库 ${item.expected}；道路不通留存 ${item.pending}。</p></details>`).join('')||'尚未征收'}</td></tr>`}).join('');
    const cargoRows=deliveries.map(cargo=>`<tr><td>${e(cargo.purpose)}／${FiscalSystem.names[cargo.resource]}</td><td>${e(state.data.cities.find(city=>city.id===cargo.sourceCityId)?.name)} → ${e(state.data.cities.find(city=>city.id===cargo.targetCityId)?.name)}</td><td>${n(cargo.amount)} → ${n(cargo.delivered)}${FiscalSystem.units[cargo.resource]}<small>路损 ${cargo.transportLoss}</small></td><td>${e(cargo.status)}<small>${cargo.status==="受阻"?"受阻":`尚需 ${Math.max(0,cargo.arriveTurn-state.turn)}日`}</small></td></tr>`).join('');
    const groups=ledger.laborGroups.filter(group=>group.forceId===state.playerForceId&&group.status==='服役'),projects=ledger.projects.filter(project=>project.forceId===state.playerForceId&&project.status==='施工');
    return `<section class="economy-forecast fiscal-summary"><header><span><small>中央钱币</small><b>${n(state.resources.gold)}贯</b></span><span><small>中央粮食</small><b>${n(state.resources.food)}石</b></span><span><small>中央布帛</small><b>${n(state.resources.silk)}品</b></span><span><small>服役徭役</small><b>${n(groups.reduce((total,group)=>total+Math.max(0,group.totalDays-group.usedDays),0))}人日</b></span></header><p>首都：${e(capital?.name||'未设置')}</p><table class="ledger-table"><thead><tr><th>资源</th><th>中央</th><th>地方</th><th>军仓</th><th>在途</th></tr></thead><tbody>${summary}</tbody></table><details><summary>征收制度</summary><p>粮食／秋收后／${account.periods.food}个月；田租 ${account.landRate}%／${account.periods.land}个月；商业税 ${account.commercialRate}%／${account.periods.commercial}个月；布帛 ${account.silkRate}%／${account.periods.silk}个月。</p></details>${this.sourceMarkup(state)}<details><summary>地方财政</summary><div class="fiscal-table-scroll"><table class="ledger-table"><thead><tr><th>城市</th><th>地方库存</th><th>效率／贪污</th><th>应收</th><th>征收明细</th></tr></thead><tbody>${rows}</tbody></table></div></details><details open><summary>在途运输（${deliveries.length}批）</summary><table class="ledger-table"><thead><tr><th>物资</th><th>路线</th><th>数量</th><th>到达</th></tr></thead><tbody>${cargoRows||'<tr><td colspan="4">无在途运输</td></tr>'}</tbody></table></details><details><summary>军队仓储</summary><table class="ledger-table"><thead><tr><th>军团</th><th>钱币／贯</th><th>粮食／石</th><th>布帛／品</th><th>日耗粮／石</th><th>就食</th></tr></thead><tbody>${army.map(army=>`<tr><td>${e(army.name)}</td><td>${n(army.stores.gold)}</td><td>${n(army.stores.food)}</td><td>${n(army.stores.silk)}</td><td>${n(FiscalSystem.armyDailyNeed(state,army))}</td><td>${this.rationMarkup(state,army)}</td></tr>`).join('')}</tbody></table></details><details><summary>徭役与工程</summary>${projects.map(project=>`<p>${e(state.data.cities.find(city=>city.id===project.cityId)?.name)} · ${e(project.name)}：${n(project.completedDays)}／${n(project.requiredDays)}人日</p>`).join('')||'<p>无在建工程</p>'}${groups.map(group=>`<p>${e(state.data.cities.find(city=>city.id===group.cityId)?.name)}：${n(group.people)}人 · ${n(group.usedDays)}／${n(group.totalDays)}人日</p>`).join('')}</details></section>`;
  }
  static open({command,state,contextCity,dialog,form,title,toast}){
    if(!["set_collection_policy","set_capital","dispatch_resources","dismiss_labor","relieve_fire","collect_tax","requisition_labor","reward_officer"].includes(command.id))return false;
    FiscalSystem.initialize(state);const e=value=>this.esc(value),account=FiscalSystem.account(state),cities=state.data.cities.filter(city=>city.force===state.playerForceId),armies=state.data.armies.filter(army=>army.force===state.playerForceId),officers=state.data.officers.filter(officer=>officer.force===state.playerForceId&&officer.status==='serving'),fields=[];
    const select=(name,label,items,value)=>fields.push({name,label,items,value}),number=(name,label,value,min=0,max=100000000)=>fields.push({name,label,value,min,max});
    if(command.id==='set_collection_policy'){
      number('landRate','田租税率 %',account.landRate,0,40);number('commercialRate','商业税率 %',account.commercialRate,0,40);number('silkRate','布帛征收率 %',account.silkRate,0,40);
      for(const [kind,label] of [['land','田租'],['commercial','商业税'],['food','粮食'],['silk','布帛']])select(`${kind}Period`,`${label}征收周期`,[1,3,6,12].map(period=>({id:String(period),name:`${period}个月`})),String(account.periods[kind]));
      select('arrears','欠缴处理',[{id:'remit',name:'补缴至首都（欠额追缴）'},{id:'retain',name:'地方留用（不再补缴）'}],account.arrears);
    }else if(command.id==='reward_officer'){
      select('officer','受赏人物',officers);select('rewardResource','赏赐物资',[{id:'gold',name:'钱币／贯'},{id:'silk',name:'布帛／品'}],'silk');number('amount','赏赐数量',20,1);
    }else{
      select('city','地方城市',cities,contextCity?.id);
      if(command.id==='collect_tax')select('resource','征收类别',[{id:'land',name:'田租／贯'},{id:'commercial',name:'商业税／贯'},{id:'food',name:'粮食／石'},{id:'silk',name:'布帛／品'}],'land');
      if(command.id==='requisition_labor'){number('amount','徭役人日',1000,1);select('projectId','投入工程',[{id:'',name:'独立征发（完成后遣散）'},...state.policies.fiscalAccounts.projects.filter(project=>project.forceId===state.playerForceId&&project.status==='施工').map(project=>({id:project.id,name:project.name}))],'')}
      if(command.id==='dispatch_resources'){select('source','物资来源',[{id:'central',name:'中央府库'},{id:'local',name:'所选城市地方库'}],'central');select('resource','调运物资',[{id:'gold',name:'钱币／贯'},{id:'food',name:'粮食／石'},{id:'silk',name:'布帛／品'}],'food');select('target','目标地方城市',cities);select('army','目标军仓（可选）',[{id:'',name:'送至目标城市地方库'},...armies],'');select('useLabor','运输劳动力',[{id:'no',name:'使用常备运输队'},{id:'yes',name:'征发徭役（人日按数量和路程计算）'}],'no');number('amount','调运数量',1000,1)}
    }
    if(fields.some(field=>field.items&&!field.items.length)){toast('没有可用目标');return true}
    title.textContent=`${command.categoryName} · ${command.name}`;
    form.innerHTML=`<p class="planner-description">${e(command.description)}</p>`+fields.map(field=>field.items?`<label>${e(field.label)}<select name="${field.name}">${field.items.map(item=>`<option value="${e(item.id)}" ${String(item.id)===String(field.value)?'selected':''}>${e(item.name)}</option>`).join('')}</select></label>`:`<label>${e(field.label)}<input name="${field.name}" type="number" min="${field.min}" max="${field.max}" step="1" value="${field.value}" required></label>`).join('')+'<div class="planner-actions"><button type="button" data-cancel>取消</button><button type="submit" class="primary">加入本日命令</button></div>';
    form.querySelector('[data-cancel]').onclick=()=>dialog.close();
    form.onsubmit=event=>{event.preventDefault();const values=Object.fromEntries(fields.map(field=>[field.name,field.items?form.elements[field.name].value:Number(form.elements[field.name].value)]));if(fields.some(field=>!field.items&&(!Number.isFinite(values[field.name])||values[field.name]<field.min||values[field.name]>field.max))){toast('数值超出允许范围');return}const cityIds=[values.city,values.target].filter(Boolean),armyIds=values.army?[values.army]:[],officerIds=values.officer?[values.officer]:[],order=state.addStructuredOrder(command.id,{cityIds,armyIds,officerIds,targetIds:[...cityIds,...armyIds,...officerIds],amount:values.amount,options:values});if(order){toast(`${command.name}已加入本日命令`);dialog.close()}};
    dialog.showModal();return true;
  }
};
